name: Test, Build and Deploy to Github Pages

on:
    push:
        branches:
            - main
            - fix-deployment-workflow

jobs:
    build:
        needs: test

        permissions:
            contents: write
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: configure github pages
              uses: actions/configure-pages@v4
              with:
                  static_site_generator: react-static
            - name: npm install
              run: npm ci
            - run: npm run build
            - name: upload artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./build"

            - name: deploy
              id: deployment
              uses: actions/deploy-pages@v4
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install
              run: npm ci
            - name: tests
              run: npm test
